const net=require('node:net'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
function parse(b,p=0){const end=b.indexOf('\r\n',p);if(end<0)return null;const type=String.fromCharCode(b[p]),s=b.subarray(p+1,end).toString();let next=end+2;if(type==='+'||type==='-'||type===':')return {value:type===':'?Number(s):s,next,error:type==='-'};if(type==='$'){const n=Number(s);if(n===-1)return{value:null,next};if(b.length<next+n+2)return null;return{value:b.subarray(next,next+n).toString(),next:next+n+2};}if(type==='*'){if(Number(s)===-1)return{value:null,next};const out=[];for(let i=0;i<Number(s);i++){const x=parse(b,next);if(!x)return null;if(x.error)throw Error(x.value);out.push(x.value);next=x.next;}return{value:out,next};}throw Error('Bad RESP');}
async function startRedis(){const bin=process.env.REDIS_TEST_SERVER;if(!bin){console.log('SKIP Redis integration: set REDIS_TEST_SERVER to a local redis-server executable.');return null;}const dir=fs.mkdtempSync(path.join(process.cwd(),'.redis-test-'));
const port=await new Promise((resolve,reject)=>{const server=net.createServer();server.on('error',reject);server.listen(0,'127.0.0.1',()=>{const p=server.address().port;server.close(()=>resolve(p))})});
const child=spawn(bin,['--bind','127.0.0.1','--port',String(port),'--save','','--appendonly','no'],{stdio:'ignore'});let error;child.on('error',e=>error=e);

 const command=args=>new Promise((resolve,reject)=>{const client=net.createConnection({host:"127.0.0.1",port}),parts=args.map(a=>Buffer.from(String(a))),chunks=[Buffer.from('*'+parts.length+'\r\n')];for(const x of parts)chunks.push(Buffer.from('$'+x.length+'\r\n'),x,Buffer.from('\r\n'));let data=Buffer.alloc(0);client.setTimeout(2000,()=>{client.destroy();reject(Error('Local Redis response timed out'))});client.on('connect',()=>client.write(Buffer.concat(chunks)));client.on('error',reject);client.on('data',b=>{data=Buffer.concat([data,b]);let x;try{x=parse(data)}catch(e){client.destroy();reject(e);return}if(x){client.end();x.error?reject(Error(x.value)):resolve(x.value)}});});
 const stop=async()=>{if(child.exitCode===null&&!error){child.kill();await new Promise(r=>child.once('exit',r))}fs.rmSync(dir,{recursive:true,force:true})};
 try{let ready=false;for(let i=0;i<100;i++){if(error)throw error;try{if(await command(['PING'])==='PONG'){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,50));}if(!ready)throw Error('Local Redis did not start');}catch(e){await stop();throw e}
 return{command,fetch:async(url,o)=>{if(url!=='https://redis.test.invalid')throw Error('Unexpected external call '+url);try{const result=await command(JSON.parse(o.body));return{ok:true,json:async()=>({result})}}catch(e){return{ok:true,json:async()=>({error:e.message})}}},stop};
}
module.exports={startRedis};
